Repository Team-DGSW-BambooForest/Bamboo-BackEnd, pull requests merged in 2023-02, with the labels that each got.

#4 Post service
  post-service/build.gradle
  post-service/src/main/java/com/bamboo/postservice/domain/post/domain/HashTag.java
  post-service/src/main/java/com/bamboo/postservice/domain/post/domain/Post.java
  post-service/src/main/java/com/bamboo/postservice/domain/post/domain/repository/HashTagRepository.java
  post-service/src/main/java/com/bamboo/postservice/domain/post/domain/repository/PostRepository.java
  post-service/src/main/java/com/bamboo/postservice/domain/post/presentation/PostController.java
  post-service/src/main/java/com/bamboo/postservice/domain/post/presentation/dto/reponse/PostListRo.java
  post-service/src/main/java/com/bamboo/postservice/domain/post/presentation/dto/reponse/PostRo.java
  post-service/src/main/java/com/bamboo/postservice/domain/post/presentation/dto/reponse/TagRo.java
  post-service/src/main/java/com/bamboo/postservice/domain/post/presentation/dto/request/PostRequest.java
  post-service/src/main/java/com/bamboo/postservice/domain/post/service/PostService.java
  post-service/src/main/java/com/bamboo/postservice/domain/repository/HashTagRepository.java
  post-service/src/main/java/com/bamboo/postservice/domain/repository/PostRepository.java
  post-service/src/main/java/com/bamboo/postservice/domain/type/PostStatus.java
  post-service/src/main/java/com/bamboo/postservice/global/annotation/AuthToken.java
  post-service/src/main/java/com/bamboo/postservice/global/client/ConfigProperties.java
  post-service/src/main/java/com/bamboo/postservice/global/exception/BusinessException.java
  post-service/src/main/java/com/bamboo/postservice/global/exception/ExceptionAdvice.java
  post-service/src/main/java/com/bamboo/postservice/global/exception/ExceptionResponse.java
  post-service/src/main/java/com/bamboo/postservice/global/exception/PostNotFoundException.java
  post-service/src/main/java/com/bamboo/postservice/global/interceptor/AuthInterceptor.java
  post-service/src/main/java/com/bamboo/postservice/global/jwt/JwtUtil.java
  post-service/src/main/java/com/bamboo/postservice/presentation/PostController.java
  post-service/src/test/java/com/bamboo/postservice/PostServiceApplicationTests.java
Labels: Feature

#8 :twisted_rightwards_arrows: :: uesr-service 작성
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/vcs.xml
  user-service/.gitignore
  user-service/build.gradle
  user-service/src/main/java/com/bamboo/userservice/UserServiceApplication.java
  user-service/src/main/java/com/bamboo/userservice/domain/auth/presentation/DauthController.java
  user-service/src/main/java/com/bamboo/userservice/domain/auth/presentation/dto/api/DOpenApiDto.java
  user-service/src/main/java/com/bamboo/userservice/domain/auth/presentation/dto/api/DodamInfoDto.java
  user-service/src/main/java/com/bamboo/userservice/domain/auth/presentation/dto/request/DAuthRequestDto.java
  user-service/src/main/java/com/bamboo/userservice/domain/auth/presentation/dto/request/LoginRequestDto.java
  user-service/src/main/java/com/bamboo/userservice/domain/auth/presentation/dto/response/DAuthResponseDto.java
  user-service/src/main/java/com/bamboo/userservice/domain/auth/presentation/dto/response/LoginResponseDto.java
  user-service/src/main/java/com/bamboo/userservice/domain/auth/service/AuthService.java
  user-service/src/main/java/com/bamboo/userservice/domain/token/presentation/TokenController.java
  user-service/src/main/java/com/bamboo/userservice/domain/token/presentation/dto/request/RefreshTokenRequestDto.java
  user-service/src/main/java/com/bamboo/userservice/domain/token/presentation/dto/response/AccessTokenResponseDto.java
  user-service/src/main/java/com/bamboo/userservice/domain/user/UserEntity.java
  user-service/src/main/java/com/bamboo/userservice/domain/user/domain/repository/UserRepository.java
  user-service/src/main/java/com/bamboo/userservice/domain/user/domain/type/Role.java
  user-service/src/main/java/com/bamboo/userservice/domain/user/presentation/UserController.java
  user-service/src/main/java/com/bamboo/userservice/domain/user/presentation/dto/response/UserResponseDto.java
  user-service/src/main/java/com/bamboo/userservice/domain/user/service/UserService.java
  user-service/src/main/java/com/bamboo/userservice/global/annotations/AuthToken.java
  user-service/src/main/java/com/bamboo/userservice/global/config/AppProperties.java
  user-service/src/main/java/com/bamboo/userservice/global/config/WebMvcConfig.java
  user-service/src/main/java/com/bamboo/userservice/global/enums/JwtType.java
  user-service/src/main/java/com/bamboo/userservice/global/exception/ExceptionAdvice.java
  user-service/src/main/java/com/bamboo/userservice/global/exception/ExceptionResponseDto.java
  user-service/src/main/java/com/bamboo/userservice/global/exception/GlobalException.java
  user-service/src/main/java/com/bamboo/userservice/global/interceptor/MyInterceptor.java
  user-service/src/main/java/com/bamboo/userservice/global/jwt/TokenProvider.java
  user-service/src/main/java/com/bamboo/userservice/global/resttemplate/RestTemplateConfig.java
  user-service/src/main/java/com/bamboo/userservice/global/resttemplate/RestTemplateErrorHandler.java
  user-service/src/main/java/com/bamboo/userservice/global/resttemplate/RestTemplateRequestInterceptor.java
  user-service/src/main/java/com/bamboo/userservice/global/util/AuthorizationUtil.java
  user-service/src/main/java/com/bamboo/userservice/presentation/UserController.java
  user-service/src/main/resources/application.yml
Labels: Duplicate, Feature

#9 Docker 파일 작성
  apigateway-service/Dockerfile
  apigateway-service/build.gradle
  apigateway-service/src/main/java/com/bamboo/apigatewayservice/ApigatewayServiceApplication.java
  apigateway-service/src/main/resources/application.yml
  config-service/Dockerfile
  config-service/build.gradle
  config-service/src/main/resources/application.yml
  config-service/src/test/java/com/bamboo/configservice/ConfigServiceApplicationTests.java
  discovery-service/Dockerfile
  discovery-service/build.gradle
  discovery-service/src/test/java/com/bamboo/discoveryservice/DiscoveryServiceApplicationTests.java
Labels: Feature

#19 Repository private 변경 후 SSH 적용
  config-service/src/main/resources/application.yml
Labels: Hotfix

#18 :twisted_rightwards_arrows: :: user-service swagger 적용
  user-service/build.gradle
  user-service/src/main/java/com/bamboo/userservice/domain/auth/service/AuthService.java
  user-service/src/main/java/com/bamboo/userservice/global/config/SwaggerConfig.java
  user-service/src/main/java/com/bamboo/userservice/global/resttemplate/RestTemplateConfig.java
  user-service/src/main/java/com/bamboo/userservice/global/resttemplate/RestTemplateErrorHandler.java
  user-service/src/main/java/com/bamboo/userservice/global/resttemplate/RestTemplateRequestInterceptor.java
  user-service/src/main/java/com/bamboo/userservice/global/webclient/WebClientConfig.java
  user-service/src/main/resources/application.yml
Labels: Refactoring

#16 post-service
  post-service/build.gradle
  post-service/src/main/java/com/bamboo/postservice/domain/post/domain/repository/HashTagRepository.java
  post-service/src/main/java/com/bamboo/postservice/domain/post/domain/repository/PostRepository.java
  post-service/src/main/java/com/bamboo/postservice/domain/post/presentation/PostController.java
  post-service/src/main/java/com/bamboo/postservice/domain/post/service/PostService.java
  post-service/src/main/java/com/bamboo/postservice/global/client/ConfigProperties.java
  post-service/src/main/java/com/bamboo/postservice/global/config/SwaggerConfig.java
  post-service/src/main/java/com/bamboo/postservice/global/interceptor/AuthInterceptor.java
  post-service/src/main/java/com/bamboo/postservice/global/jwt/JwtType.java
  post-service/src/main/java/com/bamboo/postservice/global/jwt/JwtUtil.java
  post-service/src/main/resources/application.yml
Labels: Bug, Hotfix

#31 apigateway cors 적용
  .idea/vcs.xml
  apigateway-service/src/main/resources/application.yml
Labels: Hotfix

#29 Feature/upload service
  apigateway-service/src/main/resources/application.yml
  apigateway-service/src/test/java/com/bamboo/apigatewayservice/ApigatewayServiceApplicationTests.java
  post-service/src/main/java/com/bamboo/postservice/domain/post/domain/repository/PostRepository.java
  upload-service/Dockerfile
  upload-service/build.gradle
  upload-service/src/main/java/com/bamboo/uploadservice/UploadServiceApplication.java
  upload-service/src/main/java/com/bamboo/uploadservice/domain/presentation/UploadController.java
  upload-service/src/main/java/com/bamboo/uploadservice/domain/service/UploadService.java
  upload-service/src/main/java/com/bamboo/uploadservice/global/config/AWSConfiguration.java
  upload-service/src/main/java/com/bamboo/uploadservice/global/config/AWSProperties.java
  upload-service/src/main/java/com/bamboo/uploadservice/global/config/SwaggerConfiguration.java
  upload-service/src/main/java/com/bamboo/uploadservice/global/config/WebConfiguration.java
  upload-service/src/main/resources/application.yml
  upload-service/src/test/java/com/bamboo/uploadservice/UploadServiceApplicationTests.java
Labels: Feature

#44 Change Status API 개발
  post-service/src/main/java/com/bamboo/postservice/domain/post/domain/Post.java
  post-service/src/main/java/com/bamboo/postservice/domain/post/presentation/PostController.java
  post-service/src/main/java/com/bamboo/postservice/domain/post/presentation/dto/request/ChangeStatusRequest.java
  post-service/src/main/java/com/bamboo/postservice/domain/post/service/PostService.java
  post-service/src/main/java/com/bamboo/postservice/global/exception/PostAlreadyAllowedException.java
  post-service/src/main/java/com/bamboo/postservice/global/exception/PostNotAllowedException.java
Labels: Feature

#45 :twisted_rightwards_arrows: :: admin-service 개발
  admin-service/.gitignore
  admin-service/build.gradle
  admin-service/gradle/wrapper/gradle-wrapper.jar
  admin-service/gradle/wrapper/gradle-wrapper.properties
  admin-service/gradlew
  admin-service/gradlew.bat
  admin-service/settings.gradle
  admin-service/src/main/java/com/bamboo/adminservice/AdminServiceApplication.java
  admin-service/src/main/java/com/bamboo/adminservice/doamin/admin/domain/type/Status.java
  admin-service/src/main/java/com/bamboo/adminservice/doamin/admin/feignclient/PostFeignClient.java
  admin-service/src/main/java/com/bamboo/adminservice/doamin/admin/presentation/AdminController.java
  admin-service/src/main/java/com/bamboo/adminservice/doamin/admin/presentation/dto/request/AdminRequestDto.java
  admin-service/src/main/java/com/bamboo/adminservice/doamin/admin/presentation/dto/reseponse/AdminResponseDto.java
  admin-service/src/main/java/com/bamboo/adminservice/doamin/admin/service/AdminService.java
  admin-service/src/main/java/com/bamboo/adminservice/global/annotation/AuthToken.java
  admin-service/src/main/java/com/bamboo/adminservice/global/config/FeignClientConfig.java
  admin-service/src/main/java/com/bamboo/adminservice/global/config/SwaggerConfig.java
  admin-service/src/main/java/com/bamboo/adminservice/global/config/WebMvcConfig.java
  admin-service/src/main/java/com/bamboo/adminservice/global/exception/ExceptionAdvice.java
  admin-service/src/main/java/com/bamboo/adminservice/global/exception/ExceptionResponseDto.java
  admin-service/src/main/java/com/bamboo/adminservice/global/exception/FeignError.java
  admin-service/src/main/java/com/bamboo/adminservice/global/exception/GlobalException.java
  admin-service/src/main/java/com/bamboo/adminservice/global/intercetor/HttpIntercetor.java
  admin-service/src/main/java/com/bamboo/adminservice/global/util/AuthorizationUtil.java
  admin-service/src/main/resources/application.yml
  admin-service/src/test/java/com/bamboo/adminservice/AdminServiceApplicationTests.java
  user-service/src/main/java/com/bamboo/userservice/domain/auth/presentation/dto/response/LoginResponseDto.java
  user-service/src/main/java/com/bamboo/userservice/domain/auth/service/AuthService.java
  user-service/src/main/java/com/bamboo/userservice/domain/user/domain/type/Role.java
  user-service/src/main/java/com/bamboo/userservice/global/jwt/TokenProvider.java
Labels: Feature

#46 Comment service
  comments-service/.gitignore
  comments-service/build.gradle
  comments-service/gradlew
  comments-service/gradlew.bat
  comments-service/settings.gradle
  comments-service/src/main/java/com/bamboo/commentsservice/CommentsServiceApplication.java
  comments-service/src/main/java/com/bamboo/commentsservice/domain/comment/domain/Comment.java
  comments-service/src/main/java/com/bamboo/commentsservice/domain/comment/domain/repository/CommentRepository.java
  comments-service/src/main/java/com/bamboo/commentsservice/domain/comment/presentation/CommentController.java
  comments-service/src/main/java/com/bamboo/commentsservice/domain/comment/presentation/dto/request/CommentRequest.java
  comments-service/src/main/java/com/bamboo/commentsservice/domain/comment/presentation/dto/response/CommentRo.java
  comments-service/src/main/java/com/bamboo/commentsservice/domain/comment/service/CommentService.java
  comments-service/src/main/java/com/bamboo/commentsservice/global/annotation/AuthToken.java
  comments-service/src/main/java/com/bamboo/commentsservice/global/client/ConfigProperties.java
  comments-service/src/main/java/com/bamboo/commentsservice/global/config/SwaggerConfig.java
  comments-service/src/main/java/com/bamboo/commentsservice/global/config/WebMvcCongfig.java
  comments-service/src/main/java/com/bamboo/commentsservice/global/exception/BusinessException.java
  comments-service/src/main/java/com/bamboo/commentsservice/global/exception/CommentNotFoundException.java
  comments-service/src/main/java/com/bamboo/commentsservice/global/exception/ExceptionAdvice.java
  comments-service/src/main/java/com/bamboo/commentsservice/global/exception/ExceptionResponse.java
  comments-service/src/main/java/com/bamboo/commentsservice/global/interceptor/AuthInterceptor.java
  comments-service/src/main/java/com/bamboo/commentsservice/global/jwt/JwtType.java
  comments-service/src/main/java/com/bamboo/commentsservice/global/jwt/JwtUtil.java
  comments-service/src/main/java/com/bamboo/commentsservice/global/util/TimeAgoFormatter.java
  comments-service/src/main/resources/application.yml
Labels: Feature
